# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version =			"6.0.2";
      src = {
        rev =			"378541a8ebe8a691b61c8ed1b4012c71343acfbb";
        sha256 =		"1lcl25zkqkyj5rvw9rad3n7bklpg10kmhmhkyyrgg8ql7di6wa0f";
      };
    };
    libVersion = {
      version =			"6.0.2";
      libSources = {
        symbols.rev =		"80a176076a8f3785a4cd64e55ec87f27f6fcc163";
        symbols.sha256 =	"1f57wv5b95iqd64k8ab82fvxnh5q890v7bzclmn019gl6ikisxj5";
        templates.rev =		"c9a51b852eacc3e64639548032b50edd80ddb27c";
        templates.sha256 =	"13h9ly6amiwm7zkwa2fd9730kh295ls8j95fszlfjp9rczv2yyzm";
        footprints.rev =	"c81b399054b0d3842094d7e8dfe08eb04310573a";
        footprints.sha256 =	"1xmnq2731v2afan1d08xb1qqgl5xd01v5jphi6cdmw28ri555cna";
        packages3d.rev =	"75175a21b720c59a26efce9a8c6dba3d032392a9";
        packages3d.sha256 =	"10zf8hp85ksi84cbiczsksn0ygvri4ffsa126v73nnkx6irw6nkk";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version =			"2022-03-08";
      src = {
        rev =			"e4b56ab7f12a97b0c7edfa6bb1c038e7cabcaa35";
        sha256 =		"0h3qlzx5acqan5vk7zgpqkp6lcib62dlqlry5yqpbzv5njkq66zl";
      };
    };
    libVersion = {
      version =			"2022-03-08";
      libSources = {
        symbols.rev =		"31fd1d421e8d3dd01ece7aeca210ae4b5bab93a6";
        symbols.sha256 =	"0pfma42n1ggvj8dw3b7cnmywdf57hdpziwjrih13qznq0bybx8s8";
        templates.rev =		"a27d83f0a20f0be0c1ab04b139a0c518da51a5d4";
        templates.sha256 =	"13h9ly6amiwm7zkwa2fd9730kh295ls8j95fszlfjp9rczv2yyzm";
        footprints.rev =	"c871df2c81a894bc5e91d2d517b76884d5a918aa";
        footprints.sha256 =	"0px2g9jansky0rvc0bdjylbmv8xwhc0q63g88hd2nzbknqli9f1y";
        packages3d.rev =	"6ff98426fd51d53c55bc48025d66d3d0b0c5df92";
        packages3d.sha256 =	"0ms9py93qyihxrhh9wm2ziycmdn88m36r8adx22ynjnxixw1f9ja";
      };
    };
  };
}
