# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version =			"7.0.7";
      src = {
        rev =			"dc7665e950aa0d42de36e928af48be3b060ba5d1";
        sha256 =		"1xbzf29rhqh6kl0vggdn2dblgp927096fc1lr3y4yw63b8n0qq50";
      };
    };
    libVersion = {
      version =			"7.0.7";
      libSources = {
        symbols.rev =		"c7df225d1c79b3ea842c77d928ce1f9bc1a63c5b";
        symbols.sha256 =	"1wr754m4ykidds3i14gqhvyrj3mbkchp2hkfnr0rjsdaqf4zmqdf";
        templates.rev =		"1561dd81d116a661a17147c3b941a3e96335eecc";
        templates.sha256 =	"1qi20mrsfn4fxmr1fyphmil2i9p2nzmwk5rlfchc5aq2194nj3lq";
        footprints.rev =	"ecb85886616b7a6bb957699037f6fb680ce01d30";
        footprints.sha256 =	"0xnnivlqgcyaz9qay73p43jnvmvshp2b3fbh3569j7rmgi5pn8x0";
        packages3d.rev =	"4fb0672db1d405b661d0cde8edb5d54ac0a95fc7";
        packages3d.sha256 =	"141r5wd8s1bgyf77kvb9q14cpsiwwv4zmfzwbgcd42rflsk2lcbc";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version =			"2023-09-27";
      src = {
        rev =			"3c40cb3fd39b1e2b9ada191a5f201c525270e486";
        sha256 =		"1vn5zb46flvvjhcv42xggxcb6wfg0xzz5mm5b2ks2s7fq52rhkjv";
      };
    };
    libVersion = {
      version =			"2023-09-27";
      libSources = {
        symbols.rev =		"d1c2bfa185ed2aec8aaa37c3c1b7cfa9c07fe3a6";
        symbols.sha256 =	"1ayl1v1yv1bwf4kv7a4ghs0k95ilj8gmaqghbfj6afwzqnv6hz8k";
        templates.rev =		"d7c8c3e950046c095824851880de02d4a1f63786";
        templates.sha256 =	"11582ldnv7hkljmhaym83962kixq1hjbfmdrn5laq7l4jk3l19vh";
        footprints.rev =	"6df710c65c4deeb3dfc376aa319ea6865e9ffaec";
        footprints.sha256 =	"0i9i213wg6b6w1chdkd0p2csr8cn4rs6l7c9xn8lx1hi28zh3lah";
        packages3d.rev =	"0a94ebca5a5523db9f6474c262ec3c72ea0241bc";
        packages3d.sha256 =	"1ypy2nzs1x8i98jr5kmlxfd6y592qs22aq73yl8nq0s6640fc4kk";
      };
    };
  };
}
