# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version =			"5.1.6";
      src = {
        rev =			"c6e7f7de7df655fd59b57823499efc443009de6b";
        sha256 =		"1pa3z0h0679jmgxlzc833h6q85b5paxdp69kf2h93vkaryj58622";
      };
    };
    libVersion = {
      version =			"5.1.6";
      libSources = {
        i18n.rev =		"5ad171ce5c8d90f4740517c2adecb310d8be51bd";
        i18n.sha256 =		"0qryi8xjm23ka363zfl7bbga0v5c31fr3d4nyxp3m168vkv9zhha";
        symbols.rev =		"5150eaa2a7d15cfc6bb1459c527c4ebaa66d7708";
        symbols.sha256 =	"12w3rdy085drlikkpb27n9ni7cyg9l0pqy7hnr86cxjcw3l5wcx6";
        templates.rev =		"9213d439f757e6049b7e54f3ea08272a0d0f44a9";
        templates.sha256 =	"1hppcsrkn4dk6ggby6ckh0q65qxkywrbyxa4lwpaf7pxjyv498xg";
        footprints.rev =	"a61b4e49762fb355f654e65a1c7db1aaf7bb2332";
        footprints.sha256 =	"1kmf91a5mmvj9izrv40mkaw1w36yjgn8daczd9rq2wlmd0rdp1zx";
        packages3d.rev =	"150ff1caf0b01dc04c84f4f966f4f88fedfa8f8c";
        packages3d.sha256 =	"0b9jglf77fy0n0r8xs4yqkv6zvipyfvp0z5dnqlzp32csy5aqpi1";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version =			"2020-10-04";
      src = {
        rev =			"9e115a548e5a1fa6be98f5840ef1565934d4ba5b";
        sha256 =		"0irw20z113avq9qh70f02pkrrl1flvvw45cx6l88gbrgksra9q4y";
      };
    };
    libVersion = {
      version =			"2020-10-04";
      libSources = {
        i18n.rev =		"d24af2da8cab4ce1081c401909a4a880514e5549";
        i18n.sha256 =		"0r0sv52k84sw4jxf10lrmzwmn58d2fv5h57fdrspnmvnh10q63xf";
        symbols.rev =		"4e17d7595f9691d45d97aea8ad64572652fb5bed";
        symbols.sha256 =	"0wjgqrd9l70mskiql7snbad8h4jqjy2865slwrv7ln74k3lsla2y";
        templates.rev =		"d075fd62e82d079e52ac33046a16744aeaa5a645";
        templates.sha256 =	"1frabh3p3l0k9k1ir820fnx6s2kzjlys2qkcrijs0azcy6g2w7xf";
        footprints.rev =	"7ebfa6b23cc292a56f751b7b5f4a0e12eeef69dd";
        footprints.sha256 =	"1xm8vvzzsmyxjjxj7244q5qfsj7y635a6wi6sc47s8dgvc1vs304";
        packages3d.rev =	"b8b3cfdfad88ba66f21002b3de51dc6f7d55ba5a";
        packages3d.sha256 =	"0jnr5ssndmi5y6pr3mkmzp11sd1swbz0c2l7zyyssdgdm6knvdcl";
      };
    };
  };
}
